### ISSUE TITLE
Official way to transform the UInt8Array output of Poseidon into a BigInt?

### ISSUE THREAD

**Issue by bmdelacruz** [iden3/circomlibjs#11]
In version 0.0.8, the output of poseidon is a BigInt which matches the output of a circuit. In the current version 0.1.7, it's returning a UInt8Array. I found a way to do it (see the snippet below), but is there a way to do it without directly using the `ffjavascript` library?

```js
// bn128
const F = new ffjavascript.ZqField(
  ffjavascript.Scalar.fromString(
    '21888242871839275222246405745257275088548364400416034343698204186575808495617'
  )
)
const expectedBigInt = F.fromRprLEM(poseidon([/* some input */]))
```

**Comment by manueljishi** [comment]
Hello there, 
same issue here.
Could you explain your methos a little more? Where does that string come from?
Thank you very much

**Comment by bmdelacruz** [comment]
I found one which can be used without ffjavascript. `someLEBufferToBigIntFunction` can be `ffjavascript.utils.leBuff2int` but it's easy to write it by yourself.

```js
const expectedBigInt = someLEBufferToBigIntFunction(
  poseidon.F.fromMontgomery(poseidon([/* some input */]))
)
```

**Comment by manueljishi** [comment]
Hello @bmdelacruz,
I finally managed to solve my issue (using PedersenHash), te solution was to use a mix of utils.leBuf2Int, utils.leInt2Buf and stringifyBigInts depending on the input the functions were expecting.
Hope you can manage to solve yours

**Comment by bmdelacruz** [comment]
@manueljishi, just for a reference in the future, how do you use `pedersenHash.hash` and transform its output to bigint?

I tried using it out of curiousity but I can't seem to get the same value the circuit produces. I also tried passing its output to `pedersenHash.babyJub.unpackPoint` but none of its outputs matched what I expected.

Your response would be very much appreciated.

**Comment by eigmax** [comment]
@bmdelacruz  here is how I handle this: https://github.com/0xEigenLabs/zkTX/blob/main/src/fr.rs#L63

**Comment by manueljishi** [comment]
@bmdelacruz I am using JavaScript to test my circuits, this is how I am parsing all the data https://github.com/Elpacos/Zk_voting_system/blob/main/test/generate_circuit_witness.js
Hope this helps you

**Comment by bmdelacruz** [comment]
@manueljishi Thank you very much!
