### ISSUE TITLE
Discrepancy between Poseidon hashes in circom vs circomlibjs

### ISSUE THREAD

**Issue by EmptyCrown** [iden3/circomlibjs#13]
I'm running into some issues with getting the `poseidon` hash from `circomlibjs` to match up to what is being generated from my circom circuit. 

Simply running a basic test, the following circom code outputs `3726866466909573295204180778017195060429212542252399592723041604622325297091`:
```
component hash = Poseidon(2);
hash.inputs[0] <== 4;
hash.inputs[1] <== 9;

log("hash", hash.out);
```

However, in JS, the output is `76775920680290703591279339458061373370655801884570234877842980728484382496803`:
```js
BigInt("0x" + Buffer.from(poseidon([4, 9])).toString("hex"))
```

Could someone help me point out what I'm missing here? I'm using the default `poseidon = await buildPoseidon();` and I'm on `circomlibjs@0.1.7`. Thanks!

**Comment by nanaknihal** [comment]
It seems the newer versions of circomlibjs have a different implementation of the Poseidon hash. This error was fixed when I downgraded to `circomlibjs@0.0.8` (perhaps some versions in between will work too; I haven't tried).

**Comment by eigmax** [comment]
Try to upgrade deps `circomlib` meanwhile.

**Comment by EmptyCrown** [comment]
Thanks. For reference, I figured out that the following yields the same results as the current circom version (no need to downgrade `circomlibjs`). 

```
let hashBytes = poseidon([4, 9]);
let hash = poseidon.F.toString(hashBytes);
```

**Comment by Sean4572435243** [comment]
Suggestion: If there was a github repository test that forced a equality comparison between the poseidon_wasm.js code and a poseidon circuit, it would be really helpful.  Took me weeks to pull this all together myself.

**Comment by samlaf** [comment]
> Thanks. For reference, I figured out that the following yields the same results as the current circom version (no need to downgrade `circomlibjs`).
> 
> ```
> let hashBytes = poseidon([4, 9]);
> let hash = poseidon.F.toString(hashBytes);
> ```

Thank you so much for this!! I was using `ffjavascript`'s utils.stringifyBigInts instead of F.toString(). Not sure what that method is doing, but it was returning other numbers.

js is such a pain to code with.. because we don't get suggestions. Really wishing this had been coded in ts, since vscode would have suggested poseidon.F.toString most likely.

**Comment by Arinerron** [comment]
for those inputs, I get:
- for the Solidity implementation: 3726866466909573295204180778017195060429212542252399592723041604622325297091n
- for the JS implementation: 76775920680290703591279339458061373370655801884570234877842980728484382496803n

> Thank you so much for this!! I was using ffjavascript's utils.stringifyBigInts instead of F.toString(). Not sure what that method is doing, but it was returning other numbers.

I don't see how it's possible for the `poseidon.F.toString()` to yield a different result. The functions return a different array of bytes.

**Comment by Arinerron** [comment]
Confirmed it's the JS implementation that's wrong. Should be 3726866466909573295204180778017195060429212542252399592723041604622325297091n too

**Comment by IreneBa26** [comment]
Facing the same issue. My circom code: 

```
 component hasher = Poseidon(2);  // Cryptographic hash function

  // Commitment generation
  hasher.inputs[0] <== voter_secret;
  hasher.inputs[1] <== selected_candidate_index;

  // Verify commitment matches generated hash
  vote_commitment === hasher.out;
```

voter_secret is _12345_
selected_candidate_index is _1_
vote_commitment should be _4213355460611018654523924795294902999663126022355729006200928612083214729114_

but trying to generate witness it throws an `Error: Error: Assert Failed`.

I generated the vote_commitment with this hash Poseidon online [website](https://poseidon-hash.online/).

Any suggestions is appreciated!
